spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workeredu_data?useSSL=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root123456
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    driver-class-name: com.mysql.cj.jdbc.Driver